services:
    db:
        container_name: 'db'
        image: postgres:latest
        restart: always
        environment:
            POSTGRES_DB: ${DB_DATABASE}
            POSTGRES_USER: ${DB_USERNAME}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
        ports:
            - "5432:5432"
        volumes:
            - database:/var/lib/postgresql/data
        networks:
            - texnomart
    rabbitmq:
        container_name: 'rabbitmq'
        image: rabbitmq:3-management
        restart: always
        ports:
            - "5672:5672"
            - "15672:15672"
        networks:
            - texnomart
    app:
        container_name: 'app'
        build:
            context: .
            dockerfile: docker/app/Dockerfile
        volumes:
            - .:/var/www/html
        ports:
            -   "8000:8000"
        expose:
            - "9000"
        depends_on:
            - db
        networks:
            - texnomart
    nginx:
        container_name: 'nginx'
        restart: always
        build:
            context: .
            dockerfile: docker/nginx/Dockerfile
        depends_on:
            - app
        volumes:
            - ./:/var/www/html
            - ./docker/logs/nginx/:/var/log/nginx
            - ./docker/nginx/sites/:/etc/nginx/sites-available
            - ./:/var/www/html
        ports:
            - "433:443"
            - "8080:80"
        networks:
            - texnomart
networks:
    texnomart:
volumes:
    database:
